// <auto-generated />
using System;
using System.Collections.Generic;
using LupiraMtgApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupiraMtgApi.Data.Migrations
{
    [DbContext(typeof(LupiraMtgDbContext))]
    partial class LupiraMtgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cards")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupiraMtgApi.Data.Entities.CardPrinting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("ArtPHash")
                        .HasColumnType("bigint");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.PrimitiveCollection<string[]>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ImageArtCropKey")
                        .HasColumnType("text");

                    b.Property<string>("ImageObjectKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Dictionary<string, decimal>>("Prices")
                        .HasColumnType("jsonb");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OracleId");

                    b.HasIndex("SetCode", "CollectorNumber");

                    b.ToTable("card_printings", "cards");
                });

            modelBuilder.Entity("LupiraMtgApi.Data.Entities.DeviceUser", b =>
                {
                    b.Property<Guid>("Sub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Sub");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("me_devices", "cards");
                });

            modelBuilder.Entity("LupiraMtgApi.Data.Entities.ScryfallSet", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("CardCount")
                        .HasColumnType("integer");

                    b.Property<string>("IconSvgUri")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly?>("ReleasedAt")
                        .HasColumnType("date");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("sets", "cards");
                });
#pragma warning restore 612, 618
        }
    }
}
