// <auto-generated />
using System;
using LupiraMtgApi.Pricing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupiraMtgApi.Pricing.Data.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260621183943_InitialPricesSchema")]
    partial class InitialPricesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("prices")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupiraMtgApi.Pricing.Domain.CardPriceLatest", b =>
                {
                    b.Property<string>("PrintingId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("Eur")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("EurFoil")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PrintingId");

                    b.ToTable("card_prices_latest", "prices");
                });

            modelBuilder.Entity("LupiraMtgApi.Pricing.Domain.CardPricePoint", b =>
                {
                    b.Property<string>("PrintingId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("ObservedOn")
                        .HasColumnType("date");

                    b.Property<decimal?>("Eur")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("EurFoil")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("PrintingId", "ObservedOn");

                    b.HasIndex("PrintingId");

                    b.ToTable("card_price_points", "prices");
                });
#pragma warning restore 612, 618
        }
    }
}
